from datetime import datetime
from decimal import Decimal
from typing import Optional

from pydantic import BaseModel, Field


class ReorderRecommendation(BaseModel):
    """A single reorder recommendation generated by the reorder engine."""

    sku: str
    product_name: str
    category: str = ""
    manufacturer_code: Optional[str] = None

    # Current state
    current_stock_sell_units: int = Field(..., description="On-hand in sell-units")
    daily_burn_rate: float = Field(..., description="Average daily sell-through (sell-units/day)")
    days_supply: float = Field(..., description="Days of inventory remaining")

    # Recommendation
    recommended_buy_qty: int = Field(..., description="Recommended purchase quantity in buy-units")
    recommended_buy_qty_sell_units: int = Field(
        ..., description="Equivalent sell-units for the recommended buy quantity"
    )
    days_supply_after_order: float = Field(..., description="Projected days supply after receiving order")

    # Cost estimate
    estimated_unit_cost: Optional[Decimal] = Field(None, description="Cost per buy-unit")
    estimated_total_cost: Optional[Decimal] = Field(None, description="Total estimated cost for this order")

    # Preferred suppliers (ranked)
    preferred_suppliers: list[str] = Field(
        default_factory=list,
        description="Ranked supplier names. Phase 1: from product master. Phase 2: from live comparison.",
    )

    # Metadata
    lead_time_days: int = 14
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    notes: str = ""
